import { test, expect } from '@playwright/test';

test('Prest.Project', async ({ page }) => {
    test.setTimeout(120000);
    page.setDefaultNavigationTimeout(60000);
    page.setDefaultTimeout(60000);
    
    await page.goto('https://www.edgewordstraining.co.uk/demo-site/');
    await page.locator('#menu-item-46').getByRole('link', { name: 'My account' }).click();
    await page.getByRole('textbox', { name: 'Username or email address *' }).click();
    await page.getByRole('textbox', { name: 'Username or email address *' }).fill('girishreddy646@gmail.com');
    await page.locator('#password').click();
    await page.locator('#password').fill('girish@123');
    await page.getByRole('button', { name: 'Log in' }).click();
    await page.locator('#menu-item-42').getByRole('link', { name: 'Home' }).click();
    await expect(page.locator('h1')).toContainText('Welcome');
    await page.getByRole('link', { name: 'Hoodies Hoodies (4)' }).click();
    await page.getByRole('link', { name: 'Add “Hoodie” to your cart' }).click();
    await page.getByRole('link', { name: 'Hoodie Sale! £' }).click();
    await page.getByLabel('breadcrumbs').getByRole('link', { name: 'Hoodies' }).click();
    await page.getByRole('link', { name: 'Add “Hoodie with Logo” to' }).click();
    await page.locator('#menu-item-42').getByRole('link', { name: 'Home' }).click();
    await page.getByRole('link', { name: 'Accessories Accessories (4)' }).click();
    await page.getByText('Beanie Sale! £20.00 £18.00 Add to cart').click();
    await page.getByRole('button', { name: 'Add to cart' }).click();
    await page.getByLabel('breadcrumbs').getByRole('link', { name: 'Accessories' }).click();
    await page.getByRole('link', { name: 'Add “Sunglasses” to your cart' }).click();
    // await page.getByTitle('View cart').click();
    await page.locator('#menu-item-44').getByRole('link', { name: 'Cart' }).click();
    await page.locator('#menu-item-47').getByRole('link', { name: 'Blog' }).click();
    await page.locator('#menu-item-43').getByRole('link', { name: 'Shop' }).click();
    await page.locator('#menu-item-43').getByRole('link', { name: 'Shop' }).click();
    await expect(page.getByRole('link', { name: 'Beanie Sale! £' })).toBeVisible();
    await page.getByText('Beanie Sale! £20.00 £18.00 Add to cart').click();
    await page.getByRole('button', { name: 'Add to cart' }).click();
    await page.locator('#menu-item-42').getByRole('link', { name: 'Home' }).click();
    await page.getByRole('link', { name: 'Tshirts Tshirts (4)' }).click();
    await page.getByRole('link', { name: 'Add “Long Sleeve Tee” to your' }).click();
    await page.getByText('Categories').click();
    await page.getByRole('link', { name: 'Add “Tshirt” to your cart' }).click();
    await page.locator('#menu-item-45').getByRole('link', { name: 'Checkout' }).click();
    await page.locator('#menu-item-44').getByRole('link', { name: 'Cart' }).click();
    await page.getByRole('link', { name: 'Proceed to checkout ' }).click();
    // await page.getByRole('textbox', { name: 'First name *' }).click();
    // await page.getByRole('textbox', { name: 'First name *' }).fill('Giri');
    await page.pause();
    // await page.getByRole('textbox', { name: 'Last name *' }).click();
    // await page.getByRole('textbox', { name: 'Last name *' }).fill('Babu');
    await page.getByRole('textbox', { name: 'Company name (optional)' }).click();
    await page.getByRole('textbox', { name: 'Company name (optional)' }).fill('XYZ');
    await page.getByRole('textbox', { name: 'Street address *' }).click();
    await page.getByRole('textbox', { name: 'Street address *' }).fill('Jp Nagar');
    await page.getByRole('textbox', { name: 'Apartment, suite, unit, etc' }).click();
    await page.getByRole('textbox', { name: 'Apartment, suite, unit, etc' }).fill('12th Crocs');
    await page.getByRole('textbox', { name: 'Town / City *' }).click();
    await page.getByRole('textbox', { name: 'Town / City *' }).fill('bangalauru');
    await page.getByRole('textbox', { name: 'Town / City *' }).click();
    await page.getByRole('textbox', { name: 'Town / City *' }).fill('bangaluru');
    await page.getByRole('textbox', { name: 'County (optional)' }).click();
    await page.getByRole('textbox', { name: 'County (optional)' }).fill('india');
    await page.getByRole('textbox', { name: 'Postcode *' }).click();
    await page.getByRole('textbox', { name: 'Postcode *' }).fill('560078');
    await page.getByRole('textbox', { name: 'Phone *' }).click();
    await page.getByRole('textbox', { name: 'Phone *' }).fill('1234567890');
    await page.getByRole('textbox', { name: 'Email address *' }).click();
    await page.getByRole('textbox', { name: 'Order notes (optional)' }).click();
    await page.getByText('Cash on delivery').click();
    await page.getByText('Check payments').click();
    await page.getByRole('button', { name: 'Place order' }).click();
    await page.locator('#menu-item-42').getByRole('link', { name: 'Home' }).click();
    await page.locator('#menu-item-46').getByRole('link', { name: 'My account' }).click();
    await page.getByRole('link', { name: ' Logout' }).click();
});